### ISSUE TITLE
Proposed addtion to list: pyxy3d

### ISSUE THREAD

**Issue by mprib** [natowi/CameraCalibTools#3]
Thank you for assembling this list, I'm glad to have found it. 

I have a multicamera calibration project that may be an appropriate add:

https://github.com/mprib/pyxy3d

Pyxy3d allows for charuco board creation, as wells as intrinsic and extrinsic calibration of cameras via pre-recorded footage. Visual feedback is provided throughout the process via a Qt GUI. 

It integrates with 2D landmark tracking to also calculate estimated 3D landmark position. Example trackers implement various flavors of Google's Mediapipe, though each one is built on a Tracker abstract base class to enable slotting various tracking tools into the workflow.

**Comment by natowi** [comment]
Thank you for the addition :)
